spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ndl}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: [ email, profile ]
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: [ user:email ]
            redirect-uri: "{baseUrl}/login/oauth2/code/github"
server:
  port: ${SERVER_PORT:8080}
app:
  jwt:
    secret: "change-this-dev-secret-change-this-dev-secret-32+chars"
    access-ttl-min: 1      # истечение access-токена (мин) — сокращено для теста авто-рефреша
    refresh-ttl-days: 7    # истечение refresh-токена (дней)
  rate-limit:
    default-per-minute: 120   # базовый лимит запросов в минуту на пользователя/IP
    window-seconds: 60         # длительность окна
    override:
      auth2faVerify: 10        # /auth/2fa/verify
      twofaVerifySetup: 10     # /2fa/verify-setup


